### ISSUE TITLE
CIテスト中に、アセットが見つからないというエラーに関して

### ISSUE THREAD

**Issue by yusu-ke** [yusu-ke/MonkPersonalityTestApp#115]
## 解決したいこと・達成したいものについて
GitHub Actionsで実行しているRailsアプリケーションのCIテスト中に、アセットが見つからないというエラーが発生しています。特に以下のエラーが発生しており、解決したいです。

```
The asset "favicon.ico" is not present in the asset pipeline.
The asset "castle.png" is not present in the asset pipeline.
The asset "22225678.png" is not present in the asset pipeline.
```

## 聞きたいこと・アドバイスが欲しいこと
上記の画像（`favicon.ico`, `castle.png`, `22225678.png`）は、`app/assets/images/` フォルダに存在しているにもかかわらず、テスト環境で正しく読み込まれず、`ActionView::Template::Error` というエラーが発生しています。

これらの画像がCI環境で正しく処理されるようにしたいです。

## 実装の際に参考にした資料等
https://railsdoc.com/page/config_assets_precompile
https://blog.mothule.com/ruby/rails/ruby-rails-assets-pipeline-use
https://stackoverflow.com/questions/44687819/rails-5-capybara-test-routing-error-public-assets
Capybara.asset_host の設定やアセットの扱いに関して、Rails 5と情報は古いが参考になしました。

https://zenn.dev/nakayama_bird/scraps/6cd446d756dcb7
## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
https://github.com/yusu-ke/MonkPersonalityTestApp/pull/113
`ci.yml`
```
name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

      # redis:
      #   image: redis
      #   ports:
      #     - 6379:6379
      #   options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips postgresql-client

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: set environment variables
        run: echo "GOOGLE_MAP_API=${{ secrets.GOOGLE_MAP_API }}" >> $GITHUB_ENV

      - name: Precompile assets
        run: RAILS_ENV=test bin/rails assets:precompile

      - name: Check for port conflicts and set CAPYBARA_PORT
        run: |
          PORT=4444
          if lsof -i:$PORT; then
          echo "Port $PORT is in use, killing the process"
          lsof -ti:$PORT | xargs kill -9
          fi
          CAPYBARA_PORT=3001
          echo "CAPYBARA_PORT=$CAPYBARA_PORT" >> $GITHUB_ENV
          echo "DEBUG: Capybara port set to $CAPYBARA_PORT"

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          GOOGLE_MAP_API: ${{ secrets.GOOGLE_MAP_API }}
          # REDIS_URL: redis://localhost:6379/0
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bundle exec rspec

      - name: Upload Capybara screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: capybara-screenshots
          path: tmp/capybara
          if-no-files-found: ignore
```
`spec/rails_helper.rb`
```
require 'spec_helper'
require 'capybara/rspec'

ENV['RAILS_ENV'] ||= 'test'

require_relative '../config/environment'

abort("The Rails environment is running in production mode!") if Rails.env.production?

require 'rspec/rails'
require 'devise'
require File.expand_path("spec/support/controller_macros.rb")

Dir[Rails.root.join('spec', 'support', '**', '*.rb')].each { |f| require f }

begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  abort e.to_s.strip
end
RSpec.configure do |config|
  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  config.fixture_paths = [
    Rails.root.join('spec/fixtures')
  ]


  config.use_transactional_fixtures = true

  config.include Devise::Test::IntegrationHelpers, type: :system
  config.include Devise::Test::ControllerHelpers, type: :controller
  config.include Devise::Test::IntegrationHelpers, type: :request
  config.extend ControllerMacros, type: :controller

  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

  Capybara.asset_host = 'http://localhost:3000'

  # Filter lines from Rails gems in backtraces.
  config.filter_rails_from_backtrace!

  config.include FactoryBot::Syntax::Methods

  config.before(:each, type: :system) do
    driven_by :remote_chrome
    Capybara.server_host = IPSocket.getaddress(Socket.gethostname)
    Capybara.server_port = 3001
    Capybara.app_host = "http://#{Capybara.server_host}:#{Capybara.server_port}"
    Capybara.ignore_hidden_elements = false
  end

  Capybara.register_driver :selenium_chrome_headless do |app|
    options = Selenium::WebDriver::Chrome::Options.new
    options.add_argument('--headless')
    options.add_argument('--disable-gpu')
    options.add_argument('--no-sandbox')
    options.add_argument('--window-size=1024,768')
    options.add_argument('disable-dev-shm-usage')
    options.add_argument('disable-extensions')
    Capybara::Selenium::Driver.new(app, browser: :chrome,  options: options, url: 'http://selenium:4444/wd/hub')
  end

  Capybara.javascript_driver = :selenium_chrome_headless
end

```
`config/initializers/assets.rb`
```
Rails.application.config.assets.version = "1.0"

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w[ admin.js admin.css ]
# config/initializers/assets.rb
Rails.application.config.assets.precompile += %w[ application.tailwind.css *.png *.jpg *.jpeg favicon.ico ]
Rails.application.config.assets.paths += [
    Rails.root.join("node_modules"),
    Rails.root.join("app/assets/stylesheets")
]

```
## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
（https://github.com/yusu-ke/MonkPersonalityTestApp/pull/113）
こちらのプルリクエストでは、テストを実行している内容が含まれています。しかし、試行錯誤の中で複数回コミットを行っているため、内容がわかりづらくなっています。そのため、実際のコードは以下に貼り付けて共有したいと考えています。

・`.github/workflows/ci.yml`で、テスト実行前にアセットのプリコンパイルを試みましたが、効果がありませんでした。プリコンパイル後にエラーが発生しています。
```
      - name: Precompile assets
        run: RAILS_ENV=test bin/rails assets:precompile

      - name: Check for port conflicts and set CAPYBARA_PORT
        run: |
          PORT=4444
          if lsof -i:$PORT; then
          echo "Port $PORT is in use, killing the process"
          lsof -ti:$PORT | xargs kill -9
          fi
          CAPYBARA_PORT=3001
          echo "CAPYBARA_PORT=$CAPYBARA_PORT" >> $GITHUB_ENV
          echo "DEBUG: Capybara port set to $CAPYBARA_PORT"

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          GOOGLE_MAP_API: ${{ secrets.GOOGLE_MAP_API }}
          # REDIS_URL: redis://localhost:6379/0
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bundle exec rspec

      - name: Upload Capybara screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: capybara-screenshots
          path: tmp/capybara
          if-no-files-found: ignore
```
・`config/initializers/assets.rb` にアセットをプリコンパイルする設定（`Rails.application.config.assets.precompile += %w[ application.tailwind.css *.png *.jpg *.jpeg favicon.ico ]`）を追加しましたが、依然としてアセットが見つかりません。
```
Rails.application.config.assets.version = "1.0"
Rails.application.config.assets.precompile += %w[ application.tailwind.css *.png *.jpg *.jpeg favicon.ico ]

Rails.application.config.assets.paths += [
    Rails.root.join("node_modules"),
    Rails.root.join("app/assets/stylesheets")
]
```
・`spec/rails_helper.rb` では、`Capybara` のドライバ設定を見直しましたが、ページクラッシュのエラーが発生し、解決には至りませんでした。（以下のまとめを参照をお願いします。）

### 問題　
CIテスト中に、アセットが見つからない
```
1. The asset "favicon.ico" is not present in the asset pipeline.
2. The asset "castle.png" is not present in the asset pipeline.
3. The asset "22225678.png" is not present in the asset pipeline.
```

・アプローチ１　事前にプリコンパイル
ci.yml ファイルにテスト前にアセットをプリコンパイルするように記述しましたが、クラッシュエラーが発生しました。
```
      - name: Precompile Assets
        run: RAILS_ENV=test bundle exec rails assets:precompil
( 中略)
      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          GOOGLE_MAP_API: ${{ secrets.GOOGLE_MAP_API }}
          # REDIS_URL: redis://localhost:6379/0
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bundle exec rspec
```
→ テスト実行後に`unknown error: session deleted because of page crash`
https://github.com/yusu-ke/MonkPersonalityTestApp/actions/runs/13170231325/job/36759104290?pr=113

`spec/rails_helper.rb` において、`Capybara`の設定を最適化しましたが、ブラウザがクラッシュしてしまうため、変化は見られませんでした。
```
Capybara.register_driver :selenium_chrome_headless do |app|
    options = Selenium::WebDriver::Chrome::Options.new
    options.add_argument('--headless')
    options.add_argument('--disable-gpu')
    options.add_argument('--no-sandbox')
    options.add_argument('--window-size=1024,768')
    options.add_argument('disable-dev-shm-usage')
    options.add_argument('disable-extensions')
    Capybara::Selenium::Driver.new(app, browser: :chrome,  options: options, url: 'http://selenium:4444/wd/hub')
  end
```

アプローチ2 CI設定からのプリコンパイル記述削除＆手動実行
手動でアセットプリコンパイルを実行しましたが、依然としてアセットが見つからないエラーが発生しています。
```
yusuke@Yusuke:~/my_project$ docker compose exec web bash
root@8598123ce04a:/myapp# RAILS_ENV=test bin/rails assets:precompile
DEPRECATION WARNING: Defining enums with keyword arguments is deprecated and will be removed
in Rails 8.0. Positional arguments should be used instead:

enum :role, {:general=>0, :admin=>1}
 (called from <class:User> at /myapp/app/models/user.rb:4)
yarn install v1.22.22
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.17s.
yarn run v1.22.22
$ esbuild app/javascript/*.* --bundle --sourcemap --format=esm --outdir=app/assets/builds --public-path=/assets

  app/assets/builds/application.js      269.7kb
  app/assets/builds/application.js.map  495.2kb

Done in 0.21s.
yarn install v1.22.22
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.13s.
yarn run v1.22.22
$ tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify

Rebuilding...

🌼   daisyUI 4.12.22
├─ ✔︎ 2 themes added            https://daisyui.com/docs/themes
╰─ ★ Star daisyUI on GitHub     https://github.com/saadeghi/daisyui


Done in 662ms.
Done in 1.44s.
[Avo->] Adding yarn dependencies
warning package.json: No license field
warning No license field
warning No license field
[Avo->] Linking avo.base.css to /usr/local/bundle/gems/avo-3.16.2/app/assets/builds/avo.base.css
[Avo->] Linking tailwind.preset.js to /usr/local/bundle/gems/avo-3.16.2/tailwind.preset.js

Rebuilding...

Done in 5307ms.
```
アセットが見つからないというエラーが発生。
```
1. `The asset "favicon.ico" is not present in the asset pipeline.`
2. `The asset "castle.png" is not present in the asset pipeline.`
3. ` The asset "22225678.png" is not present in the asset pipeline.`
```

プリコンパイルする設定（Rails.application.config.assets.precompile += %w[ application.tailwind.css *.png *.jpg *.jpeg favicon.ico ]）を追加しましたが、変化はありませんでした。
